---
title: "Расчет размера выборки"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(TrialSize)
```

```{r}
theme_set(theme_minimal())
```


```{r}
TwoSampleMean.NIS(
  alpha  = 0.025,
  beta   = 0.2,  
  sigma  = 0.5,    
  k      = 1,      
  delta  = -0.6,     
  margin = 0   
  )

```

```{r}
(11 / 0.8) %>% ceiling()

((11 / 0.8) / 0.9) %>% ceiling() * 2
```




```{r}
ggplot() +
  
  geom_vline(xintercept = c(-0.6, 0), linetype = 'dashed',
             colour = 'grey40', size = 1)+
  
  
  geom_segment(aes(x = -1, xend = 1, y = 0, yend = 0), 
               color = "black", size = 0.5) +  
  
  
  geom_point(aes(y = 0.3, x = 0), size = 18, color = "skyblue3", shape = 18) +
  geom_errorbar(aes(y = 0.3, xmin = -0.5, xmax = 0.5), 
                width = 0, color = "skyblue3", size = 3)+
  
  

  coord_cartesian(ylim = c(0, 0.6))+
  scale_x_continuous(breaks = c(-0.6,0,0.6))+
  theme(
    axis.text.y = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    axis.text.x = element_text(size = 25, colour = 'grey10')
  )
```


