---
title: "Графики"
author: "Oksana Plastinina"
date: "`r Sys.Date()`"
output: 
  html_document:
    number_sections: true
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
#Создание темы графиков для документа
thememine <- theme(
  plot.title = element_text(size = 15, hjust = 0.5),
  plot.subtitle = element_text(size = 16, hjust = 0.5),
  axis.title = element_text(size = 12),
  axis.text = element_text(size = 10, colour = 'grey10'),
  panel.background = element_rect(fill = 'white'),
  panel.grid = element_line(colour = 'grey90'),
  legend.text = element_text(size = 10)
)

theme_set(thememine)

ARMvalues <- c('CurcuminNEO' = 'sienna3',
               'Methotrexate' = 'seagreen' )

ARMlabels <- c('CurcuminNEO' = '"Куркумин НЕО"',
               'Methotrexate' = '"Метотрексат"' )
```

```{r}
data_cleaned <- readRDS('team3_ecrf_wide.rds')
```

# Динамика DAS28 по визитам

```{r}
data_cleaned %>% 
  select(c(USUBJID, ARM, contains('DAS_DAS28'))) %>% 
  pivot_longer(!c(USUBJID, ARM), names_to = 'VISIT', values_to = 'DAS28') %>% 
  mutate(
    VISIT = str_extract(VISIT, "\\d+"),
    VISIT = factor(VISIT, levels = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12))
  ) %>% 
  ggplot()+
  geom_line(aes(x = VISIT, y = DAS28, group = USUBJID, colour = ARM), linewidth = 1)+

  labs(
    x = 'Номер визита',
    y = 'Балл по шкале DAS28',
    title = 'Динамика баллов по шкале DAS28 каждого пациента'
  )+
  scale_colour_manual(
    values = ARMvalues,
    name = NULL,
    labels = ARMlabels
  )+
  scale_y_continuous(breaks = seq(0,6,0.5))+
  theme(
    legend.position = 'bottom',
    legend.justification = 'centre'
  )
```


# Разница между 1 и 12 визитом по шкале DAS28

```{r}
data_cleaned %>% 
  select(c(USUBJID, ARM, contains('DAS_DAS28'))) %>% 
  pivot_longer(!c(USUBJID, ARM), names_to = 'VISIT', values_to = 'DAS28') %>% 
  mutate(
    VISIT = str_extract(VISIT, "\\d+") %>% as.factor()
  ) %>% 
  filter(VISIT == 0 | VISIT == 12) %>% 
  ggplot()+
  geom_line(aes(x = VISIT, y = DAS28, group = USUBJID, color = ARM), linewidth = 0.7) +
  geom_boxplot(aes(x = VISIT, y = DAS28, fill = ARM))+
  facet_grid(.~ARM, labeller = labeller(ARM = ARMlabels))+
  labs(
    x = 'Номер визита',
    y = 'Балл по шкале DAS28',
    title = 'Динамика баллов по шкале DAS28 каждого пациента'
  )+
  scale_colour_manual(
    values = ARMvalues
  )+
  scale_fill_manual(
    values = ARMvalues
  )+
  scale_y_continuous(breaks = seq(0,6,0.5))+
  theme(
    legend.position = 'none'
  )
```

# Динамика VAS по визитам
```{r}

data_cleaned %>% 
  select(c(USUBJID, ARM, contains('PAIN_VAS'))) %>% 
  pivot_longer(!c(USUBJID, ARM), names_to = 'VISIT', values_to = 'VAS') %>% 
  mutate(
    VISIT = str_extract(VISIT, "\\d+"),
    VISIT = factor(VISIT, levels = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12))
  ) %>% 
  ggplot()+
  geom_line(aes(x = VISIT, y = VAS, group = USUBJID, colour = ARM), linewidth = 1)+
  labs(
    x = 'Номер визита',
    y = 'Балл по шкале VAS',
    title = 'Динамика баллов по шкале VAS каждого пациента'
  )+
  scale_colour_manual(
    values = ARMvalues,
    name = NULL,
    labels = ARMlabels
  )+
  scale_y_continuous(breaks = seq(0,80,10))+
  theme(
    legend.position = 'bottom',
    legend.justification = 'centre'
  )

```

# Разница между 7 и 12 визитом по шкале VAS

```{r}

data_cleaned %>% 
  select(c(USUBJID, ARM, contains('VAS'))) %>% 
  pivot_longer(!c(USUBJID, ARM), names_to = 'VISIT', values_to = 'VAS') %>% 
  mutate(
    VISIT = str_extract(VISIT, "\\d+"),
    VISIT = factor(VISIT, levels = c( 7, 12))
  ) %>% 
  filter(VISIT == 7 | VISIT == 12) %>% 
  ggplot()+
  geom_line(aes(x = VISIT, y = VAS, group = USUBJID, color = ARM), linewidth = 0.7) +
  geom_boxplot(aes(x = VISIT, y = VAS, fill = ARM), width = 0.5)+
  facet_grid(.~ARM, labeller = labeller(ARM = ARMlabels))+
  labs(
    x = 'Номер визита',
    y = 'Балл по шкале VAS',
    title = 'Динамика баллов по шкале VAS каждого пациента'
  )+
  scale_colour_manual(
    values = ARMvalues
  )+
  scale_fill_manual(
    values = ARMvalues
  )+
  scale_y_continuous(breaks = seq(0,80,10))+
  theme(
    legend.position = 'none'
  )
```







